const prompts = [
    "What do you know about Hobbits?",
    "What is quantum field theory?",
    "Why did the chicken cross the road?",
    "Who is the president of the United States?",
    "How do I run CMake on MacOS?",
    "Do you agree that C++ is a really finicky language compared with Python3?",
    "Is it a good idea to invest in technology?",
    "Do you like Wagner's Ring?",
    "Do you think this file input option is really neat?",
    "What should we all do about climate change?",
    "Is time-travel possible within the laws of current physics?",
    "Is it like anything to be a bat?",
    "Once the chicken has crossed the road, does it try to go back?",
    "Who is the greatest of all musical composers?",
    "What is art?",
    "Is there life elsewhere in the universe?",
    "What is intelligence?",
    "What is the difference between knowledge and intelligence?",
    "Will religion ever die?",
    "Do we understand ourselves?",
    "What is the best way to cook eggs?",
    "If you cannot see things, on what basis do you evaluate them?",
    "Explain the role of the np junction in photovoltaic cells?",
    "Is professional sport a good or bad influence on human behaviour?",
    "Is capital punishment immoral?",
    "Should we care about other people?",
    "Who are you?",
    "Which sense would you surrender if you could?",
    "Was Henry Ford a hero or a villain?",
    "Do we need leaders?",
    "What is nucleosynthesis?",
    "Who is the greatest scientist of all time?",
    "Who first observed what came to be known as the photovoltaic effect?",
    "What is nuclear fusion and why does it release energy?",
    "Can you know that you exist?",
    "What is an exoplanet?",
    "Do you like cream?",
    "What is the difference?",
    "Can I know that I exist while I'm dreaming that I'm Descartes?",
    "Who said 'I didn't know I thought that until I heard myself saying it'?",
    "Does anything really matter?",
    "Can you explain the unreasonable effectiveness of mathematics?",
    "What is your favorite color?",
    "Why do we dream?",
    "What makes someone truly happy?",
    "What is love?",
    "How can I improve my mental health?",
    "What is the meaning of life?",
    "How do I find my purpose?",
    "What are some tips for staying organized?",
    "How can I become more confident?",
    "What is the best way to learn a new skill?",
    "How can I manage stress better?",
    "What are some ways to make friends?",
    "How do I start a business?",
    "What is the best way to travel?",
    "What is the most important thing in life?",
    "How can I stay motivated?",
    "What are some healthy habits?",
    "What is the secret to success?",
    "How can I be more productive?",
    "What are some good books to read?",
    "How can I save money?",
    "What is the best way to exercise?",
    "How can I improve my memory?",
    "What are some fun hobbies?",
    "How can I be more creative?",
    "What is the best way to relax?",
    "What are some good movies to watch?",
    "How can I be more patient?",
    "What is the best way to communicate?",
    "How can I overcome fear?",
    "What is the best way to handle rejection?",
    "How can I be more grateful?",
    "What is the best way to apologize?",
    "How can I be more empathetic?",
    "What is the best way to resolve conflicts?",
    "How can I be more kind?",
    "What is the best way to forgive?",
    "How can I be more honest?",
    "What is the best way to set goals?",
    "How can I be more disciplined?",
    "What is the best way to prioritize tasks?",
    "How can I be more efficient?",
    "What is the best way to focus?",
    "How can I be more resilient?",
    "What is the best way to deal with failure?",
    "How can I be more optimistic?",
    "What is the best way to handle criticism?",
    "How can I be more self-aware?",
    "What is the best way to practice mindfulness?",
    "How can I be more present?",
    "What is the best way to meditate?",
    "How can I be more peaceful?",
    "What is the best way to express gratitude?",
    "How can I be more compassionate?",
    "What is the best way to show appreciation?",
    "How can I be more generous?",
    "What is the best way to give back?",
    "How can I be more humble?",
    "What is the best way to stay positive?",
    "How can I be more authentic?",
    "What is the best way to be yourself?",
    "How can I be more unique?",
    "What is the best way to stand out?",
    "How can I be more influential?",
    "What is the best way to inspire others?",
    "How can I be more persuasive?",
    "What is the best way to motivate others?",
    "How can I be more helpful?",
    "What is the best way to support others?",
    "How can I be more encouraging?",
    "What is the best way to cheer someone up?",
    "How can I be more understanding?",
    "What is the best way to listen?",
    "How can I be more attentive?",
    "What is the best way to observe?",
    "How can I be more curious?",
    "What is the best way to ask questions?",
    "How can I be more open-minded?",
    "What is the best way to embrace change?",
    "How can I be more adaptable?",
    "What is the best way to cope with uncertainty?",
    "How can I be more flexible?",
    "What is the best way to handle surprises?",
    "How can I be more spontaneous?",
    "What is the best way to have fun?",
    "How can I be more playful?",
    "What is the best way to enjoy life?",
    "How can I be more joyful?",
    "What is the best way to celebrate?",
    "How can I be more social?",
    "What is the best way to meet new people?",
    "How can I be more outgoing?",
    "What is the best way to network?",
    "How can I be more charismatic?",
    "What is the best way to connect with others?",
    "How can I be more likable?",
    "What is the best way to build rapport?",
    "How can I be more trustworthy?",
    "What is the best way to earn respect?",
    "How can I be more reliable?",
    "What is the best way to keep promises?",
    "How can I be more responsible?",
    "What is the best way to take initiative?",
    "How can I be more proactive?",
    "What is the best way to solve problems?",
    "How can I be more resourceful?",
    "What is the best way to think critically?",
    "How can I be more analytical?",
    "What is the best way to make decisions?",
    "How can I be more decisive?",
    "What is the best way to plan?",
    "How can I be more strategic?",
    "What is the best way to organize?",
    "How can I be more systematic?",
    "What is the best way to execute?",
    "How can I be more thorough?",
    "What is the best way to follow through?",
    "How can I be more consistent?",
    "What is the best way to maintain momentum?",
    "How can I be more persistent?",
    "What is the best way to stay committed?",
    "How can I be more dedicated?",
    "What is the best way to persevere?",
    "How can I be more tenacious?",
    "What is the best way to push through challenges?",
    "How can I be more brave?",
    "What is the best way to face fears?",
    "How can I be more courageous?",
    "What is the best way to stand up for myself?",
    "How can I be more assertive?",
    "What is the best way to defend my beliefs?",
    "How can I be more passionate?",
    "What is the best way to pursue my dreams?",
    "How can I be more driven?",
    "What is the best way to achieve my goals?",
    "How can I be more ambitious?",
    "What is the best way to reach my potential?",
    "How can I be more determined?",
    "What is the best way to stay focused?",
    "How can I be more engaged?",
    "What is the best way to immerse myself?",
    "How can I be more involved?",
    "What is the best way to contribute?",
    "How can I be more impactful?",
    "What is the best way to make a difference?",
    "How can I be more significant?",
    "What is the best way to leave a legacy?",
    "How can I be more remembered?",
    "What is the best way to honor my values?",
    "How can I be more ethical?",
    "What is the best way to act with integrity?",
    "How can I be more principled?",
    "What is the best way to live by my beliefs?",
    "How can I be more righteous?",
    "What is the best way to do the right thing?",
    "How can I be more just?",
    "What is the best way to treat others fairly?",
    "How can I be more equitable?",
    "What is the best way to promote equality?",
    "How can I be more inclusive?",
    "What is the best way to embrace diversity?",
    "How can I be more tolerant?",
    "What is the best way to accept differences?",
    "How can I be more respectful?",
    "What is the best way to show consideration?",
    "How can I be more polite?",
    "What is the best way to demonstrate manners?",
    "How can I be more courteous?",
    "What is the best way to show kindness?",
    "How can I be more caring?",
    "What is the best way to nurture relationships?",
    "How can I be more loving?",
    "What is the best way to strengthen bonds?",
    "How can I be more supportive?",
    "What is the best way to offer comfort?",
    "How can I be more comforting?",
    "What is the best way to provide solace?",
    "How can I be more reassuring?",
    "What is the best way to instill confidence?",
    "How can I be more encouraging?",
    "What is the best way to uplift others?",
    "How can I be more inspiring?",
    "What is the best way to motivate others?",
    "How can I be more influential?",
    "What is the best way to lead by example?",
    "How can I be more exemplary?",
    "What is the best way to showcase excellence?",
    "How can I be more exceptional?",
    "What is the best way to stand out?",
    "How can I be more unique?",
    "What is the best way to highlight my strengths?",
    "How can I be more remarkable?",
    "What is the best way to make an impression?",
    "How can I be more memorable?",
    "What is the best way to leave a lasting impact?",
    "How can I be more impactful?",
    "What is the best way to create change?",
    "How can I be more transformative?",
    "What is the best way to initiate progress?",
    "How can I be more innovative?",
    "What is the best way to foster creativity?",
    "How can I be more imaginative?",
    "What is the best way to spark ideas?",
    "How can I be more inventive?",
    "What is the best way to generate solutions?",
    "How can I be more resourceful?",
    "What is the best way to leverage opportunities?",
    "How can I be more savvy?",
    "What is the best way to navigate challenges?",
    "How can I be more strategic?",
    "What is the best way to plan ahead?",
    "How can I be more forward-thinking?",
    "What is the best way to anticipate outcomes?",
    "How can I be more predictive?",
    "What is the best way to foresee trends?",
    "How can I be more perceptive?",
    "What is the best way to notice details?",
    "How can I be more observant?",
    "What is the best way to gather information?",
    "How can I be more informed?",
    "What is the best way to stay updated?",
    "How can I be more knowledgeable?",
    "What is the best way to expand my horizons?",
    "How can I be more well-read?",
    "What is the best way to broaden my perspective?",
    "How can I be more enlightened?",
    "What is the best way to gain wisdom?",
    "How can I be more wise?",
    "What is the best way to apply lessons learned?",
    "How can I be more reflective?",
    "What is the best way to contemplate?",
    "How can I be more introspective?",
    "What is the best way to examine my thoughts?",
    "How can I be more self-aware?",
    "What is the best way to understand myself?",
    "How can I be more mindful?",
    "What is the best way to stay present?",
    "How can I be more centered?",
    "What is the best way to find balance?",
    "How can I be more balanced?",
    "What is the best way to harmonize my life?",
    "How can I be more harmonious?",
    "What is the best way to synchronize my actions?",
    "How can I be more coordinated?",
    "What is the best way to align my efforts?",
    "How can I be more aligned?",
    "What is the best way to streamline my processes?",
    "How can I be more efficient?",
    "What is the best way to optimize my workflow?",
    "How can I be more productive?",
    "What is the best way to maximize my output?",
    "How can I be more effective?",
    "What is the best way to enhance my results?",
    "How can I be more successful?",
    "What is the best way to achieve my objectives?",
    "How can I be more goal-oriented?",
    "What is the best way to focus on my targets?",
    "How can I be more targeted?",
    "What is the best way to direct my energy?",
    "How can I be more directed?",
    "What is the best way to channel my motivation?",
    "How can I be more motivated?",
    "What is the best way to ignite my drive?",
    "How can I be more driven?",
    "What is the best way to fuel my ambition?",
    "How can I be more ambitious?",
    "What is the best way to aim high?",
    "How can I be more aspirational?",
    "What is the best way to envision my future?",
    "How can I be more visionary?",
    "What is the best way to imagine possibilities?",
    "How can I be more imaginative?",
    "What is the best way to explore new ideas?",
    "How can I be more exploratory?",
    "What is the best way to venture into the unknown?",
    "How can I be more adventurous?",
    "What is the best way to embrace risks?",
    "How can I be more daring?",
    "What is the best way to take bold steps?",
    "How can I be more bold?",
    "What is the best way to challenge conventions?",
    "How can I be more unconventional?",
    "What is the best way to break boundaries?",
    "How can I be more boundary-breaking?",
    "What is the best way to redefine norms?",
    "How can I be more norm-defying?",
    "What is the best way to question assumptions?",
    "How can I be more questioning?",
    "What is the best way to challenge the status quo?",
    "How can I be more rebellious?",
    "What is the best way to disrupt existing systems?",
    "How can I be more disruptive?",
    "What is the best way to catalyze change?",
    "How can I be more catalytic?",
    "What is the best way to trigger reactions?",
    "How can I be more reactive?",
    "What is the best way to respond effectively?",
    "How can I be more responsive?",
    "What is the best way to adapt quickly?",
    "How can I be more adaptive?",
    "What is the best way to adjust to changes?",
    "How can I be more flexible?",
    "What is the best way to bend without breaking?",
    "How can I be more resilient?",
    "What is the best way to bounce back from setbacks?",
    "How can I be more perseverant?",
    "What is the best way to endure hardships?",
    "How can I be more steadfast?",
    "What is the best way to remain unwavering?",
    "How can I be more unshakable?",
    "What is the best way to stay grounded?",
    "How can I be more grounded?",
    "What is the best way to anchor myself?",
    "How can I be more anchored?",
    "What is the best way to find stability?",
    "How can I be more stable?",
    "What is the best way to cultivate consistency?",
    "How can I be more consistent?",
    "What is the best way to maintain regularity?",
    "How can I be more regular?",
    "What is the best way to establish routines?",
    "How can I be more routine-driven?",
    "What is the best way to form habits?",
    "How can I be more habitual?",
    "What is the best way to reinforce behaviors?",
    "How can I be more reinforced?",
    "What is the best way to strengthen practices?",
    "How can I be more practiced?",
    "What is the best way to perfect skills?",
    "How can I be more perfected?",
    "What is the best way to refine techniques?",
    "How can I be more refined?",
    "What is the best way to polish abilities?",
    "How can I be more polished?",
    "What is the best way to shine in performance?",
    "How can I be more outstanding?",
    "What is the best way to excel?",
    "How can I be more excellent?",
    "What is the best way to achieve greatness?",
    "How can I be more great?",
    "What is the best way to realize my full potential?",
    "How can I be more potentialized?",
    "What is the best way to unlock my capabilities?",
    "How can I be more capable?",
    "What is the best way to harness my talents?",
    "How can I be more talented?",
    "What is the best way to showcase my gifts?",
    "How can I be more gifted?",
    "What is the best way to share my blessings?",
    "How can I be more blessed?",
    "What is the best way to spread positivity?",
    "How can I be more positive?",
    "What is the best way to radiate optimism?",
    "How can I be more optimistic?",
    "What is the best way to project hope?",
    "How can I be more hopeful?",
    "What is the best way to inspire faith?",
    "How can I be more faithful?",
    "What is the best way to trust in life?",
    "How can I be more trusting?",
    "What is the best way to believe in myself?",
    "How can I be more believing?",
    "What is the best way to have confidence?",
    "How can I be more confident?",
    "What is the best way to feel secure?",
    "How can I be more secure?",
    "What is the best way to protect myself?",
    "How can I be more protected?",
    "What is the best way to safeguard my interests?",
    "How can I be more safeguarded?",
    "What is the best way to shield against harm?",
    "How can I be more shielded?",
    "What is the best way to avoid danger?",
    "How can I be more cautious?",
    "What is the best way to mitigate risks?",
    "How can I be more risk-averse?",
    "What is the best way to minimize threats?",
    "How can I be more threat-conscious?",
    "What is the best way to recognize dangers?",
    "How can I be more vigilant?",
    "What is the best way to stay alert?",
    "How can I be more alert?",
    "What is the best way to stay awake?",
    "How can I be more awake?",
    "What is the best way to stay energized?",
    "How can I be more energized?",
    "What is the best way to boost my vitality?",
    "How can I be more vital?",
    "What is the best way to enhance my vigor?",
    "How can I be more vigorous?",
    "What is the best way to increase my stamina?",
    "How can I be more stamina-filled?",
    "What is the best way to sustain my endurance?",
    "How can I be more enduring?",
    "What is the best way to persist through trials?",
    "How can I be more persistent?",
    "What is the best way to continue despite obstacles?",
    "How can I be more relentless?",
    "What is the best way to press on relentlessly?",
    "How can I be more relentless?",
    "What is the best way to push beyond limits?",
    "How can I be more limitless?",
    "What is the best way to transcend boundaries?",
    "How can I be more transcendent?",
    "What is the best way to rise above circumstances?",
    "How can I be more elevated?",
    "What is the best way to ascend to higher levels?",
    "How can I be more ascending?",
    "What is the best way to climb towards success?",
    "How can I be more climbing?",
    "What is the best way to reach new heights?",
    "How can I be more reaching?",
    "What is the best way to strive for improvement?",
    "How can I be more striving?",
    "What is the best way to seek growth?",
    "How can I be more growing?",
    "What is the best way to evolve over time?",
    "How can I be more evolving?",
    "What is the best way to transform continuously?",
    "How can I be more transforming?",
    "What is the best way to reinvent myself?",
    "How can I be more reinvented?",
    "What is the best way to renew my spirit?",
    "How can I be more renewed?",
    "What is the best way to rejuvenate my mind?",
    "How can I be more rejuvenated?",
    "What is the best way to refresh my outlook?",
    "How can I be more refreshed?",
    "What is the best way to revitalize my energy?",
    "How can I be more revitalized?",
    "What is the best way to reinvigorate my passion?",
    "How can I be more reinvigorated?",
    "What is the best way to reignite my enthusiasm?",
    "How can I be more enthusiastic?",
    "What is the best way to fuel my excitement?",
    "How can I be more excited?",
    "What is the best way to stir my emotions?",
    "How can I be more emotional?",
    "What is the best way to express my feelings?",
    "How can I be more expressive?",
    "What is the best way to convey my thoughts?",
    "How can I be more communicative?",
    "What is the best way to articulate my ideas?",
    "How can I be more articulate?",
    "What is the best way to clarify my points?",
    "How can I be more clear?",
    "What is the best way to simplify my messages?",
    "How can I be more simplified?",
    "What is the best way to streamline my communication?",
    "How can I be more streamlined?",
    "What is the best way to optimize my interactions?",
    "How can I be more optimized?",
    "What is the best way to enhance my conversations?",
    "How can I be more enhanced?",
    "What is the best way to enrich my exchanges?",
    "How can I be more enriched?",
    "What is the best way to deepen my connections?",
    "How can I be more connected?",
    "What is the best way to strengthen my bonds?",
    "How can I be more bonded?",
    "What is the best way to fortify my relationships?",
    "How can I be more fortified?",
    "What is the best way to solidify my ties?",
    "How can I be more solidified?",
    "What is the best way to cement my friendships?",
    "How can I be more cemented?",
    "What is the best way to forge stronger alliances?",
    "How can I be more forged?",
    "What is the best way to build lasting partnerships?",
    "How can I be more built?",
    "What is the best way to cultivate meaningful collaborations?",
    "How can I be more cultivated?",
    "What is the best way to nurture cooperative endeavors?",
    "How can I be more nurtured?",
    "What is the best way to support collaborative efforts?",
    "How can I be more supported?",
    "What is the best way to assist shared projects?",
    "How can I be more assisted?",
    "What is the best way to contribute to team initiatives?",
    "How can I be more contributed?",
    "What is the best way to participate in group activities?",
    "How can I be more participatory?",
    "What is the best way to engage in collective ventures?",
    "How can I be more engaged?",
    "What is the best way to immerse myself in teamwork?",
    "How can I be more immersed?",
    "What is the best way to involve myself deeply?",
    "How can I be more involved?",
    "What is the best way to dedicate myself fully?",
    "How can I be more dedicated?",
    "What is the best way to commit wholeheartedly?",
    "How can I be more committed?",
    "What is the best way to pledge my loyalty?",
    "How can I be more loyal?",
    "What is the best way to uphold my commitments?",
    "How can I be more upholding?",
    "What is the best way to adhere to my promises?",
    "How can I be more adherent?",
    "What is the best way to stick to my word?",
    "How can I be more sticking?",
    "What is the best way to maintain my integrity?",
    "How can I be more integral?",
    "What is the best way to preserve my honesty?",
    "How can I be more honest?",
    "What is the best way to embody truthfulness?",
    "How can I be more truthful?",
    "What is the best way to practice sincerity?",
    "How can I be more sincere?",
    "What is the best way to demonstrate authenticity?",
    "How can I be more authentic?",
    "What is the best way to reveal my true self?",
    "How can I be more revealing?",
    "What is the best way to unveil my genuine nature?",
    "How can I be more unveiled?",
    "What is the best way to uncover my inner essence?",
    "How can I be more uncovered?",
    "What is the best way to discover my core identity?",
    "How can I be more discovered?",
    "What is the best way to explore my inner world?",
    "How can I be more exploring?",
    "What is the best way to delve into my psyche?",
    "How can I be more delving?",
    "What is the best way to dive deep into my consciousness?",
    "How can I be more diving?",
    "What is the best way to swim in the depths of my mind?",
    "How can I be more swimming?",
    "What is the best way to float freely in my thoughts?",
    "How can I be more floating?",
    "What is the best way to drift effortlessly in my imagination?",
    "How can I be more drifting?",
    "What is the best way to sail smoothly in my creativity?",
    "How can I be more sailing?",
    "What is the best way to cruise gracefully in my innovation?",
    "How can I be more cruising?",
    "What is the best way to glide effortlessly in my ingenuity?",
    "How can I be more gliding?",
    "What is the best way to soar high in my originality?",
    "How can I be more soaring?",
    "What is the best way to fly freely in my uniqueness?",
    "How can I be more flying?",
    "What is the best way to ascend without limits?",
    "How can I be more ascending?",
    "What is the best way to transcend earthly bounds?",
    "How can I be more transcending?",
    "What is the best way to elevate my spirit?",
    "How can I be more elevating?",
    "What is the best way to lift my soul?",
    "How can I be more lifting?",
    "What is the best way to raise my consciousness?",
    "How can I be more raising?",
    "What is the best way to enlighten my mind?",
    "How can I be more enlightening?",
    "What is the best way to illuminate my understanding?",
    "How can I be more illuminating?",
    "What is the best way to brighten my perspective?",
    "How can I be more brightening?",
    "What is the best way to clarify my vision?",
    "How can I be more clarifying?",
    "What is the best way to sharpen my insight?",
    "How can I be more sharpening?",
    "What is the best way to hone my perception?",
    "How can I be more honing?",
    "What is the best way to refine my discernment?",
    "How can I be more refining?",
    "What is the best way to polish my judgment?",
    "How can I be more polishing?",
    "What is the best way to perfect my decision-making?",
    "How can I be more perfecting?",
    "What is the best way to fine-tune my choices?",
    "How can I be more fine-tuning?",
    "What is the best way to calibrate my selections?",
    "How can I be more calibrating?",
    "What is the best way to adjust my preferences?",
    "How can I be more adjusting?",
    "What is the best way to tailor my decisions?",
    "How can I be more tailoring?",
    "What is the best way to customize my approach?",
    "How can I be more customizing?",
    "What is the best way to personalize my strategy?",
    "How can I be more personalizing?",
    "What is the best way to individualize my plan?",
    "How can I be more individualizing?",
    "What is the best way to make my path unique?",
    "How can I be more unique?",
    "What is the best way to distinguish my journey?",
    "How can I be more distinguishing?",
    "What is the best way to set myself apart?",
    "How can I be more setting-apart?",
    "What is the best way to carve my own niche?",
    "How can I be more carving?",
    "What is the best way to craft my distinct identity?",
    "How can I be more crafting?",
    "What is the best way to mold my personal brand?",
    "How can I be more molding?",
    "What is the best way to shape my reputation?",
    "How can I be more shaping?",
    "What is the best way to define my character?",
    "How can I be more defining?",
    "What is the best way to outline my personality?",
    "How can I be more outlining?",
    "What is the best way to sketch my traits?",
    "How can I be more sketching?",
    "What is the best way to draw my attributes?",
    "How can I be more drawing?",
    "What is the best way to paint my qualities?",
    "How can I be more painting?",
    "What is the best way to color my features?",
    "How can I be more coloring?",
    "What is the best way to hue my characteristics?",
    "How can I be more huing?",
    "What is the best way to shade my nuances?",
    "How can I be more shading?",
    "What is the best way to tint my subtleties?",
    "How can I be more tinting?",
    "What is the best way to tone my distinctions?",
    "How can I be more toning?",
    "What is the best way to highlight my uniqueness?",
    "How can I be more highlighting?",
    "What is the best way to emphasize my individuality?",
    "How can I be more emphasizing?",
    "What is the best way to accentuate my singularity?",
    "How can I be more accentuating?",
    "What is the best way to amplify my distinctiveness?",
    "How can I be more amplifying?",
    "What is the best way to magnify my peculiarity?",
    "How can I be more magnifying?",
    "What is the best way to enlarge my particularity?",
    "How can I be more enlarging?",
    "What is the best way to expand my specificity?",
    "How can I be more expanding?",
    "What is the best way to stretch my idiosyncrasy?",
    "How can I be more stretching?",
    "What is the best way to extend my peculiarity?",
    "How can I be more extending?",
    "What is the best way to elongate my uniqueness?",
    "How can I be more elongating?",
    "What is the best way to lengthen my individuality?",
    "How can I be more lengthening?",
    "What is the best way to prolong my distinctiveness?",
    "How can I be more prolonging?",
    "What is the best way to perpetuate my peculiarity?",
    "How can I be more perpetuating?",
    "What is the best way to sustain my uniqueness?",
    "How can I be more sustaining?"
];

// Seed random function using current time
function seedRandom() {
    const seed = new Date().getTime() % 1e9; // Get milliseconds timestamp as seed
    Math.random = (function(seed) {
        return function() {
            const x = Math.sin(seed++) * 10000;
            return x - Math.floor(x);
        };
    })(seed);
}

// Function to get a random prompt
function random_prompt() {
    return prompts[Math.floor(Math.random() * prompts.length)];
}

// Seed the random function when module is loaded
seedRandom();

// Export functions and array
export { prompts, random_prompt };
