const prompts = [
    "What do you know about Hobbits?",
    "What is quantum field theory?",
    "Why did the chicken cross the road?",
    "Is it a good idea to invest in technology?",
    "What should we all do about climate change?",
    "Is time-travel possible within the laws of current physics?",
    "Is it like anything to be a bat?",
    "Once the chicken has crossed the road, does it try to go back?",
    "Who is the greatest of all musical composers?",
    "What is art?",
    "Is there life elsewhere in the universe?",
    "What is intelligence?",
    "What is the difference between knowledge and intelligence?",
    "Will religion ever die?",
    "Do we understand ourselves?",
    "What is the best way to cook eggs?",
    "If you cannot see things, on what basis do you evaluate them?",
    "Is professional sport a good or bad influence on human behaviour?",
    "Is capital punishment immoral?",
    "Should we care about other people?",
    "Which sense would you surrender if you could?",
    "Was Henry Ford a hero or a villain?",
    "Do we need leaders?",
    "Who is the greatest scientist of all time?",
    "What is nuclear fusion and why does it release energy?",
    "Can you know that you exist?",
    "What is an exoplanet?",
    "Who said 'I didn't know I thought that until I heard myself saying it'?",
    "Does anything really matter?",
    "Can you explain the unreasonable effectiveness of mathematics?",
    "What makes someone truly happy?",
    "What is love?",
    "How can I improve my mental health?",
    "What is the meaning of life?",
    "How do I find my purpose?",
    "What are some tips for staying organized?",
    "How can I become more confident?",
    "What is the best way to learn a new skill?",
    "How can I manage stress better?",
    "What are some ways to make friends?",
    "How do I start a business?",
    "What is the best way to travel?",
    "What is the most important thing in life?",
    "How can I stay motivated?",
    "What are some healthy habits?",
    "What is the secret to success?",
    "How can I be more productive?",
    "What are some good books to read?",
    "How can I save money?",
    "What is the best way to exercise?",
    "How can I improve my memory?",
    "What are some fun hobbies?",
    "How can I be more creative?",
    "What is the best way to relax?",
    "What are some good movies to watch?",
    "How can I be more patient?",
    "What is the best way to communicate?",
    "How can I overcome fear?",
    "What is the best way to handle rejection?",
    "How can I be more grateful?",
    "What is the best way to apologize?",
    "How can I be more empathetic?",
    "What is the best way to resolve conflicts?",
    "How can I be more kind?",
    "What is the best way to forgive?",
    "How can I be more honest?",
    "What is the best way to set goals?",
    "What is the best way to prioritize tasks?",
    "Design a world and its inhabitants that would be interesting to explore in a novel.",
    "Come up with 10 original ideas for a story set in the future.",
    "Create an interesting world with its own laws, customs, and creatures.",
    "Write a story about an unlikely group of characters who come together to save the world from a great evil.",
    "Make a list of challenges and obstacles for a character on their quest to find love.",
    "Compare and contrast two sources of information on a specific topic.",
    "Find research that directly supports or refutes an argument related to ",
    "How can I structure an essay?",
    "What would be the best approach to writing a paper?",
    "What are the fundamental principles of the scientific method and how are they applied in various fields of study?",
    "Explain the process of osmosis and its role in the transport of materials in living organisms.",
    "Discuss the role of the media in shaping public opinion and its impact on democracy.",
    "Outline the events and significance of the American Revolution.",
    "What are the key characteristics and features of different types of ecosystems, such as forests, deserts, and grasslands?",
    "Discuss the impact of globalization on the economy, society, and culture.",
    "Discuss the causes and effects of the Great Depression and how it was addressed through government intervention.",
    "What were the major beliefs and practices of Buddhism and how have they evolved over time?",
    "Describe the discovery and significance of plate tectonics in understanding the Earth’s geology.",
    "Explain the concept of energy and the different forms it can take, such as thermal, kinetic, and potential energy.",
    "Discuss the impact of technology on education and how it is changing the way we learn.",
    "Outline the major events and consequences of World War II.",
    "Explain the process of natural selection and how it leads to evolution.",
    "What is the role of government in regulating the economy and protecting the rights and welfare of citizens?",
    "Discuss the social, cultural, and economic changes brought about by the feminist movement.",
    "Explain the basic principles of aerodynamics and how they apply to the design of aircraft and other vehicles.",
    "What were the causes and consequences of the collapse of the Soviet Union?",
    "Discuss the impact of the Internet and social media on communication and society.",
    "Describe the key elements and beliefs of Taoism and Confucianism and how they have influenced Chinese culture and philosophy.",
    "What is the role of the judiciary in interpreting and enforcing the law?",
    "Explain the process of mitosis and meiosis and their significance in cell division and reproduction.",
    "Discuss the impact of the Green Revolution on agriculture and food production.",
    "Outline the major events and significance of the Cold War.",
    "Explain the basic principles of electromagnetism and their applications in technology and industry.",
    "What are the key theories and models in macroeconomics and how are they used to analyze the economy?",
    "Discuss the impact of immigration on society and the economy.",
    "Describe the history and evolution of jazz music and its influence on other musical genres.",
    "What were the causes and consequences of the Cuban Revolution?",
    "Explain the basic principles of thermodynamics and their applications in energy and engineering.",
    "Remember the funniest prank you ever played or were a part of? Share the story!",
    "Have you come across any conspiracy theories that are just too absurd to be true?",
    "We’ve all told a few white lies in our time. What’s the most ridiculous one you’ve ever heard or told yourself?",
    "Everyone has an embarrassing moment they’d rather forget. What’s yours?",
    "What’s the funniest movie or TV show you’ve watched lately that had you in stitches?",
    "Have you ever come across a law or rule that just doesn’t make any sense?",
    "Have you ever had a dream that was just too ridiculous to be true?",
    "What’s the most absurd food you’ve ever tried and why did you try it?",
    "What’s the most ridiculous outfit you’ve ever worn and why did you wear it?",
    "Do you have a nickname that’s so silly, it’s embarrassing to admit?",
    "Have you ever come across an autocorrect fail that had you laughing out loud?",
    "Remember an advertisement that was so absurd, it left you scratching your head?",
    "Have you ever said or done something in public that was just too ridiculous for words?",
    "We’ve all given an excuse or two in our time. What’s the most ridiculous one you’ve ever heard or given?",
    "Have you ever seen something on social media that was just too absurd to be real?",
    "Have you ever done something for love that was just too ridiculous to explain?",
    "What’s the most absurd thing you’ve ever bought or been gifted with?",
    "Have you ever seen a sports moment that was just too ridiculous to be true?",
    "Have you ever overheard someone on the phone saying something so absurd, it made you laugh?",
    "Have you ever done something for a dare that was just too ridiculous to believe?",
    "Have you ever done something to avoid paying a fine that was just too absurd to be true?",
    "Have you ever done something for a bet that was just too ridiculous to explain?",
    "Have you ever met a celebrity that was just too absurd to be real?",
    "Let’s start with a basic one – what’s the difference between a virus and bacteria?",
    "Headaches are a common issue, but do you know the most common cause of them?",
    "Exercise is great for your physical health, but have you heard about its benefits for mental health too?",
    "Anxiety can be a tough thing to deal with. Can you identify the symptoms of anxiety disorder?",
    "The common cold is a nuisance, but what steps can you take to prevent it?",
    "COVID-19 is still a concern for many of us. How does someone get tested for it?",
    "Your diet can play a big role in many aspects of your health, including heart disease. Want to know more?",
    "Staying hydrated is important, but how much water should an adult be drinking every day?",
    "Smoking is bad for you, but quitting can be difficult. What’s the most effective way to quit smoking?",
    "Depression can be overwhelming. What treatments are available for it?",
    "Meditation is becoming more and more popular, but do you know its benefits?",
    "Stress can have a negative impact on many parts of your body, including your immune system. Want to know more?",
    "Diabetes is a common health issue, but did you know there are two different types? Let’s discuss type 1 and type 2.",
    "Chemotherapy is a powerful treatment, but it also comes with side effects. Explain.",
    "High blood pressure can be dangerous, but what are some effective ways to reduce it?",
    "Alcohol is a part of many people’s lives, but how does it impact liver health?",
    "Heart attacks can be serious, but do you know the warning signs and what to do if you experience them?",
    "Chronic pain can be debilitating, but what are some ways to manage it effectively?",
    "Infertility is an issue for many couples, but what causes infertility in men and women?",
    "Steroids can be helpful in some cases, but what are the long-term effects of using them?",
    "There are many options for birth control, but what is the most effective form?",
    "Sleep and weight gain are linked, but how exactly do they impact each other?",
    "Our environment can have a big impact on our health. Want to know more?",
    "A sedentary lifestyle can be harmful to your health. Let’s talk about the dangers of it.",
    "Boosting your immune system can help keep you healthy, but what’s the best way to do it?",
    "Air pollution is a growing concern, but how does it impact respiratory health?",
    "Osteoporosis is a condition that affects bone health, but what are its symptoms?",
    "Your gut bacteria plays a big role in your overall health. Want to learn more?",
    "Stress and anxiety can be tough to manage, but what are some of the best ways to do so?",
    "Strokes can be serious, but do you know the warning signs and what to do if you experience them?",
    "What are the best spices to add to a dish to enhance its flavor?",
    "How do you properly cook a steak to achieve the perfect tenderness and flavor?",
    "What are some healthy and tasty alternatives to traditional pasta dishes?",
    "How do you make a classic tomato sauce from scratch?",
    "What are the essential tools every kitchen should have?",
    "What are some easy and quick meals to make for busy weeknights?",
    "How do you properly store fresh herbs to keep them from wilting too quickly?",
    "What are some common mistakes people make when baking cakes?",
    "What are the health benefits of cooking with coconut oil?",
    "How do you properly clean and maintain a cast iron pan?",
    "What are the different types of vinegar and how do they differ in taste and use?",
    "How do you make a vegan version of a traditional meat dish?",
    "What are some common misconceptions about gluten-free cooking and baking?",
    "How do you make a hearty and filling soup for a cold winter day?",
    "What are the best oils to use for high-heat cooking?",
    "What are some unique and interesting ways to use leftovers?",
    "How do you make a creamy and smooth Hollandaise sauce?",
    "What are some different ways to prepare and cook vegetables for maximum flavor and nutrition?",
    "How do you properly clean and store fresh mushrooms?",
    "What are some healthy and tasty snack options for work or school?",
    "How do you make a delicious and fluffy scrambled egg?",
    "What are the benefits of using fresh versus canned ingredients in cooking?",
    "How do you make a simple and flavorful marinade for grilled meats?",
    "What are some common cooking techniques used in different cuisines around the world?",
    "How do you make a traditional and authentic sushi roll?",
    "What are some tips and tricks for successful grilling and barbecuing?",
    "How do you make a flavorful and aromatic broth or stock?",
    "What are some delicious and healthy ways to use tofu in cooking?",
    "How do you make a light and crispy tempura batter?",
    "What are some different ways to cook and serve fish for a healthy and tasty meal?",
    "Looking for some great single-player games for your Xbox? Let’s explore some options.",
    "PC is the ultimate platform for multiplayer games. Let’s discover some of the most popular ones.",
    "Not all open-world games get the recognition they deserve. Let’s uncover some hidden gems.",
    "Virtual Reality is an immersive experience, and these games make the most of it.",
    "Survival games can be nail-bitingly tense. Let’s count down the best ones of all time.",
    "Mobile gaming is big business and these games are incredibly addictive.",
    "Console fighting games have come a long way. Let’s take a look at the best ones.",
    "Xbox is perfect for co-op games. Let’s find out which ones to play with your friends.",
    "PC gaming is at its best when played with friends. Here are some of the best games to try.",
    "Nintendo Switch is a versatile platform and these RPGs are just the ticket.",
    "Puzzle games can be fiendishly difficult. Let’s find the most challenging ones.",
    "Racing games are all about speed and style. Here are the best ones for PS5.",
    "Nintendo Switch is great for kids and these games will keep them entertained.",
    "Xbox is capable of some stunning graphics, and these games are the proof.",
    "PC is the king of strategy games. Let’s explore some of the best ones.",
    "Xbox is the perfect platform for horror games. Let’s dive into some of the scariest ones.",
    "PS4 is home to some great games for sports fans. Let’s find the best ones.",
    "Nintendo Switch is a relaxing platform and these games will help you unwind.",
    "PC games can be educational, and these ones are perfect for history buffs.",
    "Xbox has some great games for space enthusiasts. Let’s take a look.",
    "PS5 is packed with action games, and these are the most engaging.",
    "Nintendo Switch is perfect for adventure games. Let’s find the best ones.",
    "PC games can be musical too, and these ones are perfect for music lovers.",
    "Xbox has some great games for car enthusiasts. Let’s discover them.",
    "PS5 is home to some of the most creative sandbox games. List the most popular.",
    "Nintendo Switch has some great games for animal lovers. Let’s find them.",
    "PC games can be visually stunning, and these ones are proof.",
    "Xbox has some great games for mystery fans. Let’s explore them.",
    "PS5 has some great games for book lovers. Let’s find the best ones.",
    "Nintendo Switch is a great platform for indie games, and these are the most innovative.",
    "What are some great pet options for those who live in apartments and don’t have a lot of free time for maintenance?",
    "How can you tell if your feline friend is in discomfort?",
    "What breeds of dogs make the best companions for families with young kids?",
    "Can you recommend some strategies for stopping excessive barking in dogs?",
    "What health issues should you be aware of if you have a pet hamster?",
    "How do you effectively litter train a kitten?",
    "Are there any pets that are particularly suitable for people with allergies?",
    "What can you do if your pet struggles with separation anxiety?",
    "How do you choose the right size fish tank for your new pet fish?",
    "What are the key factors to keep in mind when thinking of getting a pet bird?",
    "What type of food is best for a pet rabbit?",
    "How often should you take your dog out for walks?",
    "What health problems should you watch out for if you have a guinea pig as a pet?",
    "How can you teach your dog some fun tricks?",
    "What pets are the best option for someone who travels frequently?",
    "How can you make sure your pet stays cool during hot weather?",
    "What are the important things to think about before getting a pet turtle?",
    "How can you prevent your cat from scratching up your furniture?",
    "What dog breeds are best for seniors?",
    "What health issues should you be aware of if you have a pet ferret?",
    "How can you help your pet adjust to a new home environment?",
    "What kind of food should you feed your pet hedgehog?",
    "How often should you take your cat for check-ups at the vet?",
    "What are the most important things to consider before getting a pet snake?",
    "How can you stop your cat from spraying inside the house?",
    "What pet reptiles are the best for someone who’s new to the world of reptile ownership?",
    "How can you help your pet deal with their fear of fireworks?",
    "What type of food is best for a pet chinchilla?",
    "How can you help your pet cope with the loss of another pet they were close to?",
    "What pet invertebrates are the easiest for beginners to care for?",
    "What are the benefits of incorporating strength training into a fitness routine?",
    "What are the best exercises for toning the legs and glutes?",
    "What are the key elements of a healthy diet?",
    "What is the recommended daily water intake for adults?",
    "What are the benefits of yoga for mental and physical health?",
    "What is the best way to lose weight in a healthy and sustainable manner?",
    "How does poor posture affect our health and how can it be corrected?",
    "What is the impact of stress on our physical and mental health?",
    "How can we maintain good gut health and prevent digestive problems?",
    "What are some common causes of chronic pain and how can it be treated?",
    "What is the recommended amount of sleep for adults and children?",
    "How can we improve our mental health through exercise and physical activity?",
    "What are the dangers of sedentary behavior and how can it be prevented?",
    "What is the best way to stay hydrated during intense physical activity?",
    "How can proper nutrition boost immunity and prevent illness?",
    "What are the most effective ways to quit smoking?",
    "What are the long-term effects of alcohol consumption on the body?",
    "How can we improve our balance and prevent falls as we age?",
    "What are the most common sports injuries and how can they be prevented?",
    "What is the role of nutrition in maintaining a healthy pregnancy?",
    "How can we improve our mental wellness through mindfulness and meditation?",
    "What are the benefits of cold therapy and how can it be used for recovery and pain management?",
    "What are the best exercises for improving cardiovascular endurance?",
    "How can we prevent and manage type 2 diabetes through lifestyle changes?",
    "What is the impact of poor nutrition on children’s growth and development?",
    "How can we prevent and treat lower back pain?",
    "What are the best exercises for improving flexibility and mobility?",
    "How can we improve our posture and reduce back pain through ergonomics?",
    "What are the best methods for stress management and relaxation?",
    "What is dark matter and how is it detected?",
    "Can you explain the theory of evolution by natural selection?",
    "What is quantum mechanics and how does it differ from classical mechanics?",
    "What is the difference between photosynthesis and cellular respiration?",
    "What is the process of cloning and how does it work?",
    "Can you use simple language to tell me about the structure and function of XYZ?",
    "What is the cause of climate change and how can it be addressed?",
    "What is the process of nuclear fusion and why is it important?",
    "How do vaccines work and why are they important for public health?",
    "What is the difference between renewable and non-renewable energy sources?",
    "Can you explain the greenhouse effect and its impact on the Earth’s climate?",
    "How does the human brain process and store information?",
    "What is the Big Bang theory and how does it explain the origin of the universe?",
    "Can you explain the process of digestion and how the body absorbs nutrients?",
    "What is the water cycle and how does it affect weather patterns?",
    "Can you explain the process of photosynthesis in plants?",
    "What is the difference between a virus, bacterium, and fungus?",
    "How does the body’s immune system protect against disease?",
    "What is the difference between atomic and molecular elements?",
    "Can you explain the process of transpiration in plants?",
    "What is the difference between physical and chemical changes in matter?",
    "How do nerve impulses transmit information in the body?",
    "What is the process of osmosis and why is it important in biology?",
    "Can you explain the difference between endothermic and exothermic reactions?",
    "What is the structure and function of the heart in the circulatory system?",
    "How do plants and animals adapt to their environment?",
    "What is the process of cell division and why is it important?",
    "Can you explain the structure and function of the respiratory system?",
    "What is the process of photosynthesis and how does it provide energy for living organisms?",
    "Can you explain the difference between positive and negative feedback in biological systems?",
    "What is the difference between machine learning and deep learning?",
    "How does blockchain technology work and what are its applications?",
    "What is the future of artificial intelligence and how will it affect our daily lives?",
    "What is 5G technology and what are its implications for the future of communication?",
    "How does virtual reality technology work and what are its practical uses?",
    "What is the Internet of Things and what impact will it have on our lives?",
    "How do data privacy and security work in cloud computing?",
    "What are some current trends in cybersecurity and how to stay protected online?",
    "What is quantum computing and how is it different from classical computing?",
    "How do drones work and what are the benefits and challenges of using them?",
    "What is augmented reality and how is it different from virtual reality?",
    "How can machine learning be used to improve healthcare and medicine?",
    "What is the future of work and how will technology impact the job market?",
    "What are some ethical considerations in the development and use of AI and robotics?",
    "What is blockchain and how does it impact the financial industry?",
    "How can machine learning be used to improve energy efficiency and sustainability?",
    "What is the role of big data in decision making and how can it be used effectively?",
    "What are some best practices for managing and protecting sensitive data in the digital age?",
    "What is the role of AI in automating processes and optimizing operations in various industries?",
    "What is the future of autonomous vehicles and how will it impact transportation and logistics?",
    "What is the impact of AI on job displacement and how can it be mitigated?",
    "How does 5G technology impact the development of the Internet of Things?",
    "What are some of the challenges and limitations of machine learning and AI?",
    "What is the future of digital identity and how will it impact personal privacy and security?",
    "How can machine learning be used to tackle environmental problems and improve sustainability?",
    "What is the future of smart cities and how will technology transform urban life?",
    "What is the impact of AI on human creativity and how can it be leveraged for artistic expression?",
    "How can machine learning be used to improve education and enhance the learning experience?",
    "What is the future of e-commerce and how will technology impact online shopping and retail?",
    "How can machine learning be used to tackle global problems such as poverty, inequality, and climate change?",
];

// Seed random function using current time
function seedRandom() {
    const seed = new Date().getTime() % 1e9; // Get milliseconds timestamp as seed
    Math.random = (function(seed) {
        return function() {
            const x = Math.sin(seed++) * 10000;
            return x - Math.floor(x);
        };
    })(seed);
}

// Function to get a random prompt
function random_prompt() {
    return prompts[Math.floor(Math.random() * prompts.length)];
}

// Seed the random function when module is loaded
seedRandom();

// Export functions and array
export { prompts, random_prompt };
